#default stuff for directory info
STFDIR = $(shell pwd | awk -F 'stf' '{$$2="";print $$1}')stf/
STFBINDIR = $(STFDIR)/bin/
STFINCLUDEDIR = $(STFDIR)/include/
DOCDIR = $(STFDIR)/doc/
EXECBASENAME = stf

NBODYDIR = $(STFDIR)/NBodylib/
NBODYSRCDIR = $(NBODYDIR)/src/
NBODYLIBDIR = $(NBODYDIR)/lib/
NBODYINCLUDEDIR = $(NBODYDIR)/include/

#type of system, where libraries are located, etc
SYSTEM="intel-standard"
SYSTEM="gcc-standard"

#For the following options, to turn off simply comment out

#what parallel options to turn on
MPI="on"
OMP="on"

#adjust precision
#SINGLEPRECISION="on"
LONGINT="on"

#Adjust the structure of the data
#do not store the mass as all particles are the same mass
#NOMASS="on"
#use single precision to store positions,velocities, and possibly other internal properties
#SINGLEPARTICLEPRECISION="on"

#Adjust the opertion of the code
#reduce impact of MPI memory overhead at the cost of extra cpu cycles
#MPIREDUCE="on"
#only calculate local density distribution for particles residing in field objects (but using all particles to estimate quantity)
STRUCTUREDEN="on"
#or just use particles inside field objects, reducing cpu cycles but will bias estimates for particle in outer region of field structures, overrides STRUCTUREDEN
#HALODEN="on"
#flag useful for zoom simulations with a high resolution region
#ZOOMSIM="on"

#for debugging
#DEBUG="on"

#for gadget format flags, that is double precision pos and vel, single precison mass, long ids, header type
#GLONGID="on"
GDPOS="on"
#GSMASS="on"
#GHEAD2="on"
#for gadget files that contain extra hydro info
#GSPHINFO="on"
#GSTARINFO="on"
#GBHINFO="on"

#for hdf input
HDFINPUT="on"

#if libraries are local
LOCALGSL="on"
LOCALFFTW="on"
LOCALHDF="on"

#for hydro simulations on can turn on several extra data structures in the Particle class, used when compiling the NBody library
#activate gas
#USEGAS="on"
#activate stars only
#USESTARS="on"
#also bh associated physics
#USEBH="on"
#stars and gas
#USEBARYONS="on"
#also use cosmic ray quantities
#USECOSMICRAYS="on"
#activate everytyhing
USEHYDRO="on"

ifeq ($(LOCALGSL),"on")
    GSL_DIR = 
    GSL_INCL =  
    GSL_LIBS =  
    GSL_CONFIG = 
    GSL_CFLAGS =
endif
ifeq ($(LOCALFFTW),"on")
    FFTW_DIR =  
    FFTW_INCL =  
    FFTW_LIBS =   
    FFTW_CFLAGS =  
endif
ifeq ($(HDFINPUT)$(LOCALHDF),"on""on")
    HDF_DIR = /home/pelahi/myresearch/SSimPL-DEDM/codes/hdf5-1.8.13
    HDF_INCL = -I$(HDF_DIR)/include/
    HDF_LIBS = -L$(HDF_DIR)/lib/
endif

ifeq ($(SYSTEM),"intel-standard")

    C+ = icc -Kc++
    COMPILEFLAGS = -O2
endif
ifeq ($(SYSTEM),"gcc-standard")
    C+ = g++
    COMPILEFLAGS = -O2
endif

ifeq ($(MPI),"on")
ifeq ($(SYSTEM),"cray")
    C+ = CC
    PARALLEL+=-DUSEMPI
else
    C+ = mpic++
    MPI_COMPILE_FLAGS = $(shell $(C+) --showme:compile)
    MPI_LINK_FLAGS = $(shell $(C+) --showme:link)
    PARALLEL+=-DUSEMPI $(MPI_COMPILE_FLAGS)
endif
endif

ifeq ($(OMP),"on")
ifeq ($(SYSTEM),"intel-standard")
    PARALLEL += -openmp -DUSEOPENMP
else ifeq ($(SYSTEM),"cray")
    PARALLEL += -DUSEOPENMP
else
    PARALLEL += -fopenmp -DUSEOPENMP
endif
endif

ifeq ($(SYSTEM)$(MPI)$(OMP),"intel-standard""on""on")
    PARALLEL += -mt_mpi
endif

ifeq ($(NOMASS),"on")
    COMPILEFLAGS+= -DNOMASS
endif

#related to precision of calculations, integers
ifeq ($(SINGLEPRECISION),"on")
    COMPILEFLAGS+= -DSINGLEPRECISION
endif
ifeq ($(LONGINT),"on")
    COMPILEFLAGS+= -DLONGINT
endif

ifeq ($(NOMASS),"on")
    COMPILEFLAGS+= -DNOMASS 
endif

ifeq ($(SINGLEPARTICLEPRECISION),"on")
    COMPILEFLAGS+= -DLOWPRECISIONPOS 
endif

C+FLAGS = $(PARALLEL) $(COMPILEFLAGS)

#Adjust calculations
ifeq ($(MPIREDUCE),"on")
    C+FLAGS+= -DMPIREDUCEMEM
endif
ifeq ($(STRUCTUREDEN),"on")
ifneq ($(HALODEN),"on")
    C+FLAGS+= -DSTRUCDEN
endif
endif
ifeq ($(HALODEN),"on")
    C+FLAGS+= -DHALOONLYDEN
endif
ifeq ($(ZOOMSIM),"on")
    C+FLAGS+= -DHIGHRES
    ZOOMNAME=-zoom
endif

ifeq ($(DEBUG),"on")
    C+FLAGS+= -g
endif

ifeq ($(GLONGID),"on")
    C+FLAGS+= -DGADGETLONGID
endif
ifeq ($(GDPOS),"on")
    C+FLAGS+= -DGADGETDOUBLEPRECISION
endif
ifeq ($(GSMASS),"on")
    C+FLAGS+= -DGADGETSINGLEMASSPRECISION
endif
ifeq ($(GHEAD2),"on")
    C+FLAGS+= -DGADGET2FORMAT
endif

ifeq ($(GSPHINFO),"on")
    C+FLAGS+= -DEXTRASPHINFO
endif
ifeq ($(GSTARINFO),"on")
    C+FLAGS+= -DEXTRASTARINFO
endif
ifeq ($(GBHINFO),"on")
    C+FLAGS+= -DEXTRABHINFO
endif

ifeq ($(HDFINPUT),"on")
    C+FLAGS+= -DUSEHDF
    C+LIBS+= -lhdf5_hl_cpp -lhdf5_cpp -lhdf5_hl -lhdf5 -lz -lrt -ldl
    IFLAGS+= $(HDF_INCL)
    LFLAGS+= $(HDF_LIBS)
endif


ifeq ($(USEBARYONS),"on")
    USEGAS="on"
    USESTARS="on"
endif
ifeq ($(USEHYDRO),"on")
    USEGAS="on"
    USESTARS="on"
    USEBH="on"
endif

ifeq ($(USEGAS),"on")
    HYDROFLAGS+= -DGASON
    GASNAME=gas
endif
ifeq ($(USESTARS),"on")
    HYDROFLAGS+= -DSTARON
    STARNAME=star
endif
ifeq ($(USEBH),"on")
    HYDROFLAGS+= -DBHON
    BHNAME=bh
endif
HYDRONAME=-$(GASNAME)$(STARNAME)$(BHNAME)

COMPILEFLAGS+= $(HYDROFLAGS)

NBODYPARALLEL = 
NBODYC+FLAGS = $(NBODYPARALLEL) $(COMPILEFLAGS) -c

EXEC = $(EXECBASENAME)$(HYDRONAME)$(ZOOMNAME)

IFLAGS += -I$(NBODYINCLUDEDIR) -I$(STFINCLUDEDIR) $(GSL_INCL)
LFLAGS += -L$(NBODYLIBDIR) $(GSL_LIBS) $(MPI_LINK_FLAGS)
C+LIBS += -lm -lAnalysis -lKD -lNBody -lMath -lgsl -lgslcblas
NBODYIFLAGS = -I$(NBODYSRCDIR)/Math/ -I$(NBODYSRCDIR)/NBody/ -I$(NBODYSRCDIR)/Analysis/ -I$(NBODYSRCDIR)/Cosmology/ -I$(NBODYSRCDIR)/InitCond/ -I$(NBODYSRCDIR)/KDTree $(GSL_CFLAGS) #-I$(BOOST_INCL) -I$(MPI_INCL)

LIBCHECK=$(NBODYDIR)/*
